config/routes.rb
Rails.application.routes.draw do

  get '/' => 'sessions#welcome'
  
  get '/signup' => 'users#new'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  
  delete '/logout', to: 'sessions#destroy', as: 'delete_user_session' #delete_user_session_path

  get '/auth/facebook/callback' => 'sessions#create'
  
  get '/most_reviewed' => 'cities#most_reviewed' #custom route to display show page for most reviewed city
  resources :users do
    resources :reviews
  end

  resources :cities do
    resources :reviews, only:[:new, :index, :show]
  end

  resources :countries do
    resources :cities, only:[:show]
  end

  resources :reviews
  resources :countries, only:[:index, :show]
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/country.rb
class Country < ApplicationRecord
    #validation did not work when referencing id in nested table
    validates :name, presence: true, uniqueness: true
    
    has_many :cities
    has_many :reviews, through: :cities

    scope :sorted, -> {order("countries.name ASC")}
    
    private

    
end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController
    before_action :redirect_if_not_logged_in


    def new
        @country = Country.new
    end

    def create
        @country = Country.new(country_params)
        if @country.save
            redirect_to new_city_path
        else
            flash[:errors] = @country.errors.full_messages
            render :new
        end
    end

    def index
        @countries = Country.all.sorted
    end

    def show
        @country = Country.find(params[:id])
    end

    

    private

    def country_params
        params.require(:country).permit(:name)
    end

end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/views/countries/index.html.erb
<h1> Countries </h1>

<ul>
    <% @countries.each do |country| %>
        <li><%= link_to country.name, country_path(country) %>
        </li>
    <% end %>
</ul>

app/views/countries/new.html.erb
<h1> Create a New Country: </h1>

<%= form_for(@country) do |f| %>
    <div>
    <%= f.label :name, 'Country Name: ' %>
    <%= f.text_field :name %>
    </div>

    <%= f.submit 'Create Country' %>
<% end %>

app/views/countries/show.html.erb
<h1><%= @country.name %></h1>

<% @country.cities.each do |city| %>
    <%= link_to city.name, country_city_path(@country, city) %> 
    - number of reviews: 
    <%= city.reviews.count %><br>
    <%= city.average_city_rating%><br><br>
<% end %>