config/routes.rb
Rails.application.routes.draw do

  get '/' => 'sessions#welcome'
  
  get '/signup' => 'users#new'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  
  delete '/logout', to: 'sessions#destroy', as: 'delete_user_session' #delete_user_session_path

  get '/auth/facebook/callback' => 'sessions#create'
  
  get '/most_reviewed' => 'cities#most_reviewed' #custom route to display show page for most reviewed city
  resources :users do
    resources :reviews
  end

  resources :cities do
    resources :reviews, only:[:new, :index, :show]
  end

  resources :countries do
    resources :cities, only:[:show]
  end

  resources :reviews
  resources :countries, only:[:index, :show]
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/city.rb
class City < ApplicationRecord
  validates :name, presence: true

  belongs_to :country
  
  has_many :reviews
  has_many :users, through: :reviews

  accepts_nested_attributes_for :country



  scope :search, -> (query) { query ? City.where("name LIKE ?", "%#{query}%") : City.all }
  scope :most_reviewed_city, -> { City.joins(:reviews).group("cities.id").order('COUNT(reviews.id) DESC').limit(1)}
  

  def city_state_country
    "#{self.name},  #{country.name}"
  end

  def average_city_rating
    if self.reviews.count(:rating) == 0
      "Be the first to rate this city!"
    else
      self.reviews.average(:rating).to_f.round(1) #TODO convert to glyphies stars in view
    end
  end

  def city_review_count
    self.reviews.count(:id)
  end


end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
    before_action :redirect_if_not_logged_in

    def new
        @city = City.new
        @city.build_country
    end

    def create
        @city = City.new(city_params)
        if @city.save
            flash[:success] = "City Successfully Created!"
            redirect_to new_user_review_path(current_user)
        else
            @city.build_country
            flash[:errors] = @city.errors.full_messages
            render :new
        end
    end

    def index
        @cities = City.search(params[:query]).order(:name) # TODO CURRENTLY ORDER BY COUNTRY ID, WANT TO SORT BY COUNTRY THEN CITY
    end

    def show
        @city = City.find(params[:id])
    end

    def destroy
        @city = City.find(params[:id])
        @city.destroy
        redirect_to country_path
    end

    def most_reviewed
        @city = City.most_reviewed_city
    end

    private

    def city_params
        params.require(:city).permit(:name, :country_id, country_attributes:[:name])
    end
    
    def find_country
        @country = Country.find_by(id: params[:country_id])
    end
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/views/cities/index.html.erb
<h1> Cities </h1>

    <%= form_tag  cities_path(@city), method: "get" do %>
        <%= text_field_tag :query %>
        <%= submit_tag :search, class: 'btn' %>
    <% end %>
<ol>
<%= "TODO DISPLAY CITIES ORGANIZED UNDER COUNTRIES"%><br><br>
<% @cities.each do |city| %>
    <h6><%= link_to city.city_state_country, city_path(city)%></h6> Number of Review(s): <%= city.reviews.count %>  <br>
    Average City Rating: <%= city.average_city_rating %><br><br>
    
<% end %>
</ol>

app/views/cities/most_reviewed.html.erb
<h1> This is the most reviewed city: </h1>

<% @city.each do |city|%>
<%= city.city_state_country %>

<% end %>

app/views/cities/new.html.erb
<h1> Add a new city: </h1>

<%= form_for(@city) do |f| %>
    <p> Select Country Location of City: </p>

    <div>
    <%= f.label :country_id %>
    <%= f.collection_select(:country_id, Country.order('name ASC'), :id, :name, :include_blank => true)%>
    </div><br>
    
    <p> Don't see your Country? <%= link_to "Create Country Here", new_country_path %> </p>

    <div>
    
    <%# could not get this to work with the collection select %>
    <%#= f.fields_for :country do |c|%>
        <%#= c.label :name, 'Country Name' %>
        <%#= c.text_field :name %>
    <%# end %>
    </div> 

    <div>
    <%= f.label :name, 'City Name: ' %>
    <%= f.text_field :name %>
    </div>

    <%= f.submit %>
<% end %>

app/views/cities/show.html.erb
<h1><%= @city.city_state_country %></h1>
<h4><%= " #{@city.average_city_rating} average rating from #{@city.city_review_count} reviews "%></h4>
<br>

<%#= link_to "Delete City", city_path, :method => 'delete' %> <%# Not using in this iteration %>
<p>
<%= link_to "Create Review for #{@city.city_state_country}", new_city_review_path(@city) %>
</p>

<p><%= link_to "All Reviews for #{@city.city_state_country}", city_reviews_path(@city) %></p><br>


    <h5><%= "Most Recent Reviews for #{@city.city_state_country}" %></h5>
        <% @city.reviews.most_recent.limit(5).each do |review|  %>
            <%= review.title %><br> <%# TO DO ADD LINK TO REVIEW %>
            <%= review.created_at.strftime("%m/%d/%Y at %I:%M%p") %><br>
            <% if review.rating != nil %>
                Rating: <%= review.rating %><br>
            <% end %>
            <%= review.content %><br><br>
        <% end %>


