config/routes.rb
Rails.application.routes.draw do

  get '/' => 'sessions#welcome'
  
  get '/signup' => 'users#new'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  
  delete '/logout', to: 'sessions#destroy', as: 'delete_user_session' #delete_user_session_path

  get '/auth/facebook/callback' => 'sessions#create'
  
  get '/most_reviewed' => 'cities#most_reviewed' #custom route to display show page for most reviewed city
  resources :users do
    resources :reviews
  end

  resources :cities do
    resources :reviews, only:[:new, :index, :show]
  end

  resources :countries do
    resources :cities, only:[:show]
  end

  resources :reviews
  resources :countries, only:[:index, :show]
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    before_action :redirect_if_not_logged_in
    before_action :set_user
    before_action :find_review, except: [:index, :new, :create]

    def new
        if find_city
            @review = @city.reviews.build
        else
            @review = Review.new
        end
    end

    def create
        @review = current_user.reviews.build(review_params)
        if @review.save
            flash[:success] = "Review Saved!"
            redirect_to user_reviews_path(current_user)
        else
            flash[:errors] = @review.errors.full_messages
            render :new
        end
    end

    def show
        # set_user
        # find_review
    end

    def index
        if @user = User.find_by_id(params[:user_id])
            @reviews = @user.reviews.most_recent
        elsif @city = City.find_by_id(params[:city_id])
            @reviews = @city.reviews.top_rated
        else
            @reviews = Review.most_recent
        end
    end

    def edit
        # set_user
        # find_review
        redirect_to user_reviews_path(current_user) unless @user.id == @review.user_id
    end

    def update
        # set_user
        # find_city
        # find_review
        if @review.update(review_params)
            redirect_to review_path(@review) #user_reviews_path(@user) redirects to all user's reviews
        else
            render :edit
        end
    end

    def destroy
        # set_user
        # find_city
        # find_review
        @review.destroy
        redirect_to user_reviews_path(@user)
    end

    private

    def find_user
        @user = User.find_by(id: params[:user_id])
    end

    def find_city
        @city = City.find_by(id: params[:city_id])
    end

    # def find_country
    #     @country = Country.find_by(id: params[:country_id])
    # end

    def find_review
        @review = Review.find_by(id: params[:id])
    end
    
    def review_params
        params.require(:review).permit(:user_id, :rating, :title, :content, :city_id, city_attributes:[:name, :country_id], country_attributes:[:name]) #TO DO ADD STATE, :state, :state_id OR state_attributes: [:name], :country_id, country_attributes: [:name])
    end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_form.html.erb
<%= form_for [user, review] do |f|%>
    
    <% if params[:city_id] %>
        <%= f.hidden_field :city_id %>
    <% else %>
        <div class="input-field">
            <%= f.label :city, "Select a city:" %>
            <%= f.collection_select :city_id, City.order('name ASC'), :id, :city_state_country, :include_blank => true %>
        </div>
        
        <p> Don't See Your City? Create new city: </p>
        
        <div class= "input-field">
            <%= link_to "Create City", new_city_path %>
        </div>
    <% end %>

    <%= f.hidden_field :user_id %>
    
    <div class="input-field">
        <%= f.label :title %>
        <%= f.text_field :title %>
    </div>

    <div class="input-field">
        <%= f.label :content %>
        <%= f.text_area :content %>
    </div>

    <div class="input-field">
        <%= f.label :rating %>
        <%= f.select :rating, (1..5), :include_blank => true %>
    </div>

    <%= f.submit button_name, class: "btn" %>
<% end %>

app/views/reviews/edit.html.erb
<h1> Edit Review </h1>
<%= render partial: 'form', locals: { review: @review, button_name: "Update Review", user: @user}%>

app/views/reviews/index.html.erb
<% if @city %>
        <h1> <%= @city.name %>, <%= @city.country.name %></h1>
        <h4><%= " #{@city.average_city_rating} average rating " %></h4>
        <p>
        <%= link_to "Create Review for #{@city.city_state_country}", new_city_review_path(@city) %>
        </p>
<% elsif @user %>
        <h1> <%= @user.name %>, here are your reviews! </h1>
<% else %>
        <h1> Reviews for All Cities </h1><br>
<% end %><br>

<% @reviews.each do |review| %>
    <h4><%= link_to review.title,  review_path(review) %></h4>
    <h5><%= review.city.city_state_country %></h5>
    <h6> Rating: <%= review.rating %>/5</h6>
    Author: <%= review.user.name %><br>
    <%= review.created_at.strftime("%m/%d/%Y at %I:%M%p") %><br><br>

<% end %>

app/views/reviews/new.html.erb
<h1> New Review <%= "for #{@city.city_state_country}" if @city %></h1>
<p>
<%= render partial: 'form', locals: {user: @user, review: @review, button_name: "Create Review"}%>


</p>

app/views/reviews/show.html.erb
<h1><%= @review.title %></h1> 
<h5><% if @review.user != current_user %> 
        By: <%= @review.user.name %>
    <% end %>
</h5><br>
<%# REFACTORED FROM TWO LINES %> <%# @review.city.name%> <%# @review.city.country.name %>
<h4> <%= @review.city.city_state_country %>  </h4>

<p>
Rating: <%= @review.rating %><br>
<br>
<%= @review.content %>
</p>

<% if @review.user == current_user %>
        <%= link_to "Edit Review", edit_review_path(@review) %>
        <%= link_to "Delete Review", review_path, :method => 'delete' %>
<% end %><br>
