config/routes.rb
Rails.application.routes.draw do

  get '/' => 'sessions#welcome'
  
  get '/signup' => 'users#new'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  
  delete '/logout', to: 'sessions#destroy', as: 'delete_user_session' #delete_user_session_path

  get '/auth/facebook/callback' => 'sessions#create'
  
  get '/most_reviewed' => 'cities#most_reviewed' #custom route to display show page for most reviewed city
  resources :users do
    resources :reviews
  end

  resources :cities do
    resources :reviews, only:[:new, :index, :show]
  end

  resources :countries do
    resources :cities, only:[:show]
  end

  resources :reviews
  resources :countries, only:[:index, :show]
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_errors.html.erb
<% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>



</footer>

app/views/layouts/_nav.html.erb
<nav >
    <div>
        
        <ul>
            <% if is_logged_in? %>
                <%= link_to "iTravel", user_path(current_user) %> - <%= current_user.name%>
                <%= link_to "Create Travel Review", new_user_review_path(current_user) %>
                <%= link_to "Your Reviews", user_reviews_path(current_user)%>
                <%= link_to "All Reviews", reviews_path %>
                <%= link_to "View Cities", cities_path %> 
                <%= link_to "View Countries", countries_path %> 
                <%= link_to "Logout", delete_user_session_path, method: 'delete' %>
                <%= link_to "Most Reviewed City", most_reviewed_path %>
            <% else %>
                <%= link_to "Log In", login_path %>
                <%= link_to "Sign Up", signup_path %>
            <% end %>
        </ul>
    </div>
</nav>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <title>iTravel</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/nav'%>
    <div class="container">
      <%= render 'layouts/errors' %>
      <%= yield %>
    </div>
    <br><br><br>
    <%= render 'layouts/footer' %>
  </body>
</html>